### ISSUE TITLE
[Star Ocean The Second Story R] 60fps Stuttering.

### ISSUE THREAD

**Issue by 7gxycn08** [StevensND/switch-port-mods#1]
When the mod is enabled the game keeps stuttering without affecting the frame times. 
Anyway to fix this issue?

**Comment by StevensND** [comment]
> When the mod is enabled the game keeps stuttering without affecting the frame times. Anyway to fix this issue?

Here are the things that I'd need to know:

**1. What emulator are you using: Yuzu or Ryujinx?**. If you aren't using emulator but you're using Switch: These mods are mainly for emulator, not for Switch. I have no idea about performance on Switch.

**In case you're using Yuzu**: Mainline or EA? Also, I would need to know which version you are using (just in case you are using an older version and you don't know it).

**In case you're using Ryujinx**: Be sure you're running the latest Ryujinx version.

**2. Are you using SteamDeck or PC?**: As on Switch, I don't have a SteamDeck to test the performance but [here is a video](https://youtu.be/FpKKm5MU_QY?si=XhTNyAJmONAtLxfb) from a person who tested the mod on SteamDeck and maybe he can help you more than me.

**3. In case you are using a PC: What CPU, GPU and RAM do you have?.**

Here are the [minimum requirements for Yuzu](https://yuzu-emu.org/help/quickstart/#hardware-requirements) to be able to use Yuzu. If you don't meet them, I would not continue emulating Switch.

Here are the [minimum requirements for Ryujinx](https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#system-requirements). Same as Yuzu.

4.  If you meet the minimum requirements, do the following test: **Disable/delete the mod and disable Vsync** (You can do this by pressing Control U in Yuzu or F1/clicking on the Vsync text (it should appear in red) in Ryujinx. Play for a while (around 15-30 mins) and see if you still have stuttering. If you don't experience stuttering, proceed to the next step.

[The game should run like this
](https://youtu.be/xmbBSDgtZ18?si=iMce15RQDzasWTt3)
**5. Enable the mod again. Did you try to clean your shaders cache before?**. If not, do it. Sometimes doing this improves performance.

**6. Finally, I would need a screenshot or a video where I can see all your settings.** You might have some strange settings that is causing this.

Another tip I could give you as an alternative to the mod is to disable Vsync and limit your FPS using the Nvidia or AMD Control Panel and set it to 60. Test if you still have stuttering. If after all this you are still having problems, I would say that the problem is your PC.

**Comment by 7gxycn08** [comment]
> > When the mod is enabled the game keeps stuttering without affecting the frame times. Anyway to fix this issue?
> 
> Here are the things that I'd need to know:
> 
> **1. What emulator are you using: Yuzu or Ryujinx?**. If you aren't using emulator but you're using Switch: These mods are mainly for emulator, not for Switch. I have no idea about performance on Switch.
> 
> **In case you're using Yuzu**: Mainline or EA? Also, I would need to know which version you are using (just in case you are using an older version and you don't know it).
> 
> **In case you're using Ryujinx**: Be sure you're running the latest Ryujinx version.
> 
> **2. Are you using SteamDeck or PC?**: As on Switch, I don't have a SteamDeck to test the performance but [here is a video](https://youtu.be/FpKKm5MU_QY?si=XhTNyAJmONAtLxfb) from a person who tested the mod on SteamDeck and maybe he can help you more than me.
> 
> **3. In case you are using a PC: What CPU, GPU and RAM do you have?.**
> 
> Here are the [minimum requirements for Yuzu](https://yuzu-emu.org/help/quickstart/#hardware-requirements) to be able to use Yuzu. If you don't meet them, I would not continue emulating Switch.
> 
> Here are the [minimum requirements for Ryujinx](https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#system-requirements). Same as Yuzu.
> 
>     4. If you meet the minimum requirements, do the following test: **Disable/delete the mod and disable Vsync** (You can do this by pressing Control U in Yuzu or F1/clicking on the Vsync text (it should appear in red) in Ryujinx. Play for a while (around 15-30 mins) and see if you still have stuttering. If you don't experience stuttering, proceed to the next step.
> 
> 
> [The game should run like this ](https://youtu.be/xmbBSDgtZ18?si=iMce15RQDzasWTt3) **5. Enable the mod again. Did you try to clean your shaders cache before?**. If not, do it. Sometimes doing this improves performance.
> 
> **6. Finally, I would need a screenshot or a video where I can see all your settings.** You might have some strange settings that is causing this.
> 
> Another tip I could give you as an alternative to the mod is to disable Vsync and limit your FPS using the Nvidia or AMD Control Panel and set it to 60. Test if you still have stuttering. If after all this you are still having problems, I would say that the problem is your PC.

I did clean my shader cache and it solved the issue now it's working like the default 30fps mode.
Thanks.
